Выполнила задание 10
htmlacademy-javascript/982097-kekstagram-21 pull request #4
Opened 2020-10-14 06:53 UTC by tonyamaksimets

2020-10-14 10:36 UTC, 4err requested changes
Вообще подставлять выбранную картинку еще рано, но отличная работа. 

При смене фильтров, всегда должен быть максимальный уровень выбран. Также нужно реализовать изменение насыщенности фильтра по клику на полоску.

2020-10-14 10:36 UTC, 4err commented on js/main.js
> +    class: `effects__preview--chrome`,
Это избыточный параметр, т.к. класс всегда равен `effects__preview--название эффекта`.

2020-10-14 10:36 UTC, 4err commented on js/main.js
> +    scale += 25;
Магическое число Ж)

2020-10-16 02:50 UTC, tonyamaksimets commented on js/main.js
> +
Управление с клавиатуры для доступности =)

2020-10-16 05:36 UTC, 4err commented on js/main.js
> +
Это здорово, только мышкой то так и не работает :( Нужно при клике на любое место полоски применять эффект согласно уровню этого места и перемещать туда пин.

2020-10-17 16:53 UTC, merged